### ISSUE TITLE
get_template_list() is lacking parameters

### ISSUE THREAD

**Issue by reidransom** [hellosign/hellosign-python-sdk#10]
The method [`get_template_list()`](https://github.com/HelloFax/hellosign-python-sdk/blob/3f2043b260f27f29a6fd4cf7a17cd05cdff2f46b/hellosign_sdk/hsclient.py#L707) only takes the `page` argument even though the documentation lists more parameters:

https://www.hellosign.com/api/reference#Template

It would be great to be able to pass `account_id`, `page_size` and `query` as well.

**Comment by benjdezi** [comment]
Thanks for reporting this, I'm going to patch this up.

**Comment by benjdezi** [comment]
@reidransom I've pushed a patch for this, take a look at version 3.8.3 of the wrapper.
