### ISSUE TITLE
Getting the contents of a signature request file

### ISSUE THREAD

**Issue by arshsingh** [hellosign/hellosign-python-sdk#12]
The `get_signature_request_file` method takes a filename, fetches the contents from the server and writes to this filename. This is a problem if the file is not stored locally (S3 in my case).

Potential solutions:
1. Make `get_signature_request_file` also accept a writable file-like object.
2. Make the `filename` parameter optional, and in it's absense return the contents as a string ?

I'd be happy to submit a PR if we can decide on a solution. I prefer the first one above, unless anyone else can propose a better solution.

**Comment by benjdezi** [comment]
I think the first solution is best, feel free to submit a pull request for it.
