### ISSUE TITLE
Add auto-retry for 409 response with GET calls

### ISSUE THREAD

**Issue by radhack** [hellosign/hellosign-python-sdk#18]
With a large-scale implementation where multiple users may be online with a platform at one time, there's a large probability that two or more users are going to trigger either GET /siganture_request/list or GET /template/list calls at the same time. Right now, the second+ of those users are going to trigger a 409 response, so it'd be helpful if you automatically handled 409 retries since my platform can't make the calls in parallel.

**Comment by alexmac05** [comment]
We currently have a plan to fork the python SDK into two.
https://github.com/hellosign/hellosign-python-sdk3 (hasn't been created yet)
and
https://github.com/hellosign/hellosign-python-sdk

When we move maintenance to hellosign-python-sdk3 we will evaluate this enhancement request.
