### ISSUE TITLE
Add support for Decline to Sign

### ISSUE THREAD

**Issue by desmondw** [hellosign/hellosign-python-sdk#20]
The following changes have been made to the API:
- There is a new parameter allow_decline for declining to sign signature requests
- There is a new API status_code for declined requests
- There is a new API variable is_declined on SignatureRequest objects
- There is a new API variable decline_reason on Signature objects

**Comment by rawadtraboulsi** [comment]
any progress or news on this? as we require the allow_decline for our user flow

**Comment by alexmac05** [comment]
Added decline to sign January 27, 2019. Internal issue as-59

**Comment by alexmac05** [comment]
This support has been added
