### ISSUE TITLE
Add HTTP mocks for test_mode

### ISSUE THREAD

**Issue by ivansabik** [hellosign/hellosign-python-sdk#22]
It would be great to use HTTP mocks for testing or enable some dev mode that doesn't actually hit the API. Something like this is working for me with [Responses](https://github.com/getsentry/responses):

```python
import responses

HS_SEND_SIGN_REQ_URL = 'https://api.hellosign.com/v3/signature_request/send'
HERE = os.path.dirname(os.path.abspath(__file__))


@responses.activate
def test_post_new_mail_signature_request():
  mock_path = os.path.join(HERE, 'mocks/signature_request_send.json')
  mock_response = open(mock_path, 'r').read()
  responses.add(responses.POST, HS_SEND_SIGN_REQ_URL,
                body=mock_response, status=200,
                content_type='application/json')

  client = HSClient(api_key='')
  signature_request = client.send_signature_request(
      test_mode=True,
      title='',
      subject='',
      message='',
      signers=[{'name': '', 'email_address': ''}],
      files=[filepath]
  )
```

And the file `signature_request_send.json` looks something like this with the actual JSON response:

```javascript
{
    "signature_request": {
    }
}
```

So an extra parameter called maybe when instancing a client like `HSClient(api_key=api_key, mock_http=True)` would be nice and I think also for some tests, it might not be ideal to hit the actual API.

**Comment by alexmac05** [comment]
We currently have a plan to fork the python SDK into two.
https://github.com/hellosign/hellosign-python-sdk3 (hasn't been created yet)
and
https://github.com/hellosign/hellosign-python-sdk

When we move maintenance to hellosign-python-sdk3 we will evaluate this enhancement request.

**Comment by alexmac05** [comment]
closing for now, but I am putting this on an enhancement list for consideration in the future. We agree this would be a great thing to have on the Python SDK. We just currently do not have the resources to implement this.
