### ISSUE TITLE
form_fields_per_document in send_signature_request is not JSON serialized automatically

### ISSUE THREAD

**Issue by klardotsh** [hellosign/hellosign-python-sdk#26]
This seems like a pretty simple oversight - passing a plain old Python list into this named param causes a 400 Bad Request exception, because the server can't parse the JSON in this field (because it's never JSON to begin with). Manually running the list through `json.dumps` before passing to the SDK fixes the problem.

3.8.5

**Comment by neillom** [comment]
Submitted fix for this issue to master.

**Comment by alexmac05** [comment]
https://github.com/hellosign/hellosign-python-sdk/pull/61 has been requested to be merged and we will test after it is merged.

**Comment by oconnor-sn** [comment]
PR 61 has been merged Jan 24th.
Can this issue be closed out? @alexmac05

**Comment by alexmac05** [comment]
merged 1/24
