### ISSUE TITLE
Source code does not adhere to PEP8 style guide

### ISSUE THREAD

**Issue by alikashani** [hellosign/hellosign-python-sdk#31]
``
def send_signature_request_with_template(self, test_mode=False, template_id=None, template_ids=None, title=None, subject=None, message=None, signing_redirect_url=None, signers=None, ccs=None, custom_fields=None, metadata=None, ux_version=None):
    ''' Creates and sends a new SignatureRequest based off of a Template
``

Right away, within this method definition we can see two glaring PEP8 violations:

1. The first line (``def send..``) goes on beyond the 120 character limit.
2. The docstring is violating the "Triple double-quoted strings should be used for docstrings"

PEP8 style guide can be found here: https://www.python.org/dev/peps/pep-0008/

**Comment by alexmac05** [comment]
Thank you for these comments. HelloSign is working to improve this SDK very soon. It is on the short term road map. Thank you for mentioning this. Please keep the suggestions coming.

**Comment by alexmac05** [comment]
Documented in internal issue number 435106 which will be used for roadmap planning of the python SDK.
