### ISSUE TITLE
client.get_oauth_data is resulting in error message

### ISSUE THREAD

**Issue by alexmac05** [hellosign/hellosign-python-sdk#32]
response = client.get_oauth_data(
                client_id=clientID,
                client_secret=secret,
                code='0369fXXXXXXXXX',
                state='b0XXX'
            )

results in 'Failed No JSON object could be decoded' message

**Comment by neillom** [comment]
I have run multiple tests with this call and all have been successful with a HSAccessTokenAuth object returned containing valid oauth token and related information.

I think this one can be called invalid/not reproducible and closed out as such

**Comment by alexmac05** [comment]
working for me as well. Closing the issue. Must have been an issue that was incorrectly assigned to the Python SDK by me. 

responseOauth = client.get_oauth_data(
    client_id='CLIENT ID',
    client_secret='SECRET',
    code='CodeFromOauthAuthorization',
    state='StateFromOauthAuthorization'
)

accessToken = responseOauth.access_token
print(accessToken)
