### ISSUE TITLE
Non-embedded signature requests should send client id for white-labeling

### ISSUE THREAD

**Issue by alexmac05** [hellosign/hellosign-python-sdk#40]
Non-embedded signature requests should send client id for white-labeling

Workaround:

import requests

buildTheRequest = 'https://' + apikey + \
 ':@api.hellosign.com/v3/signature_request/send'

data = {
 'client_id': clientID,
 'file_url': 'https://i.ytimg.com/vi/JPA_rzHDy6o/maxresdefault.jpg',
 'subject': 'test production',
 'allow_decline': '1',
 'message': 'test',
 'signers[0][name]': 'George',
 'signers[0][email_address]': 'petir@example.com',
 'signers[1][name]': 'Ed',
 'signers[1][email_address]': 'fletcher.ed@example.com',
 'test_mode': '1'

}

print(buildTheRequest)   

r = requests.post(buildTheRequest, data)
print(r.text)
stringData = r.text

**Comment by erosiec** [comment]
Tested successfully on version 3.8.9 with the following: 

def send():
    files = ["Test.pdf"]
    signers = [
        {"name": "Signer", "email_address": signer_email_address},
    ]
    signature_request = client.send_signature_request(
                                test_mode=True,
                                files=files,
                                client_id = client_id,
                                file_urls=None,
                                title="test title",
                                subject="test subject",
                                message="test message",
                                signing_redirect_url=None,
                                signers=signers)
