### ISSUE TITLE
HSClient.get_template_edit_url doesn't take a test_mode parameter

### ISSUE THREAD

**Issue by elizabethkilson** [hellosign/hellosign-python-sdk#5]
When using the function as suggested in the documentation, I get permission errors that suggest using test_mode=1, but the function in the python sdk won't take it as a parameter. Is there another way I should be using the test mode?

**Comment by BHSPitMonkey** [comment]
Hi,

In this SDK, you can enable test mode using an optional parameter called `test_mode`. For example:

``` python
# Send a signature request with remote files
signature_request = client.send_signature_request(
                                test_mode=True, 
                                files=None, 
                                file_urls=["http://www.example.com/download/sample.pdf"], 
                                title="NDA with Acme Co.", 
                                subject="The NDA we talked about", 
                                message="Please sign this NDA and then we can discuss more. Let me know if you have any questions.", 
                                signing_redirect_url=None, 
                                signers=signers, 
                                cc_email_addresses=cc_email_addresses)
```

Cheers!

**Comment by elizabethkilson** [comment]
Hi,

I've seen that on other functions. The problem is that get_template_edit_url doesn't accept the parameter test_mode. As in
client.get_template_edit_url(template_id, test_mode=True)
throws
get_template_edit_url() got an unexpected keyword argument 'test_mode'

I've gotten the code to work by doing
client.get_template_edit_url(template_id + "?test_mode=1")
but I imagine you want your sdk to offer a better solution.

**Comment by cmpaul** [comment]
This is actually something we need to figure out on the back-end. This endpoint should be available despite test_mode, since it's simply retrieving an existing template for embedded editing. I'll keep you posted.

p.s., Thanks for the PR!
