### ISSUE TITLE
Abandonware?

### ISSUE THREAD

**Issue by bclermont** [hellosign/hellosign-python-sdk#55]
Is this library unmaintained?
There is multiple unreviewed and un merged pull requests.
Outdated API calls.

**Comment by souldeux** [comment]
I'd like to point at this PR specifically as an example of why anyone examining this repo would think it abandoned: https://github.com/hellosign/hellosign-python-sdk/pull/42

**Comment by alexmac05** [comment]
We are trying hard to get some resources onto this SDK. We hope to have some news soon.

**Comment by bclermont** [comment]
@alexmac05 just grant write access to some community members to maintains the code instead of discourage open source collaboration

**Comment by alexmac05** [comment]
Hi Bruno and others who have commented on this thread, 

We have documented this request to have our SDKs support continuous integration to make them more contribution friendly. We are currently working on a sprint to clear up all open issues. Thank you so much for reaching out. 

I am going to close this issue for now as it isn't possible in the short term to open our the SDK currently. Also, we are making our way through all the pull requests. 

Thank you,
alex

HS Internal issue number 435093 for the request to make this open to continuous integration. If anyone has questions about the status of that please reference this number.
