### ISSUE TITLE
signing_options causing malformed JSON request when attempting to send a signature request

### ISSUE THREAD

**Issue by neillom** [hellosign/hellosign-python-sdk#58]
Since the merge yesterday any attempt to create a signature request will throw a malformed JSON error when attempting to process the request.

This is due to the json.dumps call during the payload creation on an empty dict. This causes the the payload to contain a null value which is returned as a 400 error.

I have a commit for this issue which I will push later tomorrow.

**Comment by alexmac05** [comment]
Tested sending a signature request with version 3.8.9 and this issue does not exist in that version. 
print(client.version) is how you can find the version

**Comment by alexmac05** [comment]
Tested sending a signature request with version 3.8.9 and this issue does not exist in that version.
print(client.version) is how you can find the version

**Comment by erosiec** [comment]
Tested sending a signature request with version 3.8.9 and this issue does not exist in that version.
print(client.version) is how you can find the version
