### ISSUE TITLE
python SDK version 3.8.8 is requiring signing options

### ISSUE THREAD

**Issue by alexmac05** [hellosign/hellosign-python-sdk#59]
signing_options = {“draw”: True, “type”: True, “upload”: True, “phone”: False, “default”: “draw”},

python SDK version 3.8.8 is requiring signing options

However, that should not be a required field. This issue does not exist in python sdk version 3.8.7

**Comment by neillom** [comment]
This was fix by the last merge, see issue 58

**Comment by alexmac05** [comment]
Tested and this issue is resolved in python SDK version 3.8.9. You can find version with this line print(client.version)

**Comment by erosiec** [comment]
Tested with version 3.8.9 and confirmed that signing_options are no longer required.

**Comment by alexmac05** [comment]
Tested and this issue is resolved in python SDK version 3.8.9. You can find version with this line print(client.version)
