### ISSUE TITLE
No way to set a timeout which can cause app to hang during an outage

### ISSUE THREAD

**Issue by realplatanopapi** [hellosign/hellosign-python-sdk#85]
Hello,

I was looking into setting a timeout for requests made with the hellosign python sdk so that our app can handle Hellosign outages more gracefully and timeout instead of hanging forever, but from what I can tell from the documentation and source code, that does not seem possible right now.

I am happy to submit a PR for this, but I wanted to make sure this repo is still actively maintained before investing the time to do that- it looks like the last commit to master at the time of this writing was on March 31: https://github.com/hellosign/hellosign-python-sdk/commit/43b0a5af6ee1d12572a7c370ec37c8ad033c6ca2

**Comment by clickclickonsal** [comment]
+1

**Comment by gpopoteur** [comment]
Hi @realplatanopapi, I'm currently the maintainer for this repo and yes it is still actively maintained. Feel free to create the PR for this feature, I will discuss with the team to prioritize this request.
